spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

comments:
  url:
    base: http://localhost:9595/api/comments
    postComments: ${comments.url.base}/{0}/post
    saveComments: ${comments.url.base}/saveAll

logging:
  level:
    org.zalando.logbook: trace   # response va request uchun log yozadi
    org:
      springframework:
        web:
          client:
            RestTemplate: trace
logbook:
    exclude:
      - /api/posts/create        # shu url uchun log yozishni taqiqlaydi