spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payme
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
