spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    properties:
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      spring.json.trusted.packages: com.fasterxml.jackson.databind.node


  datasource:
    url: jdbc:postgresql://localhost:5432/payme
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

uz-common-kafka:
  config-simulate: false
  topics:
    order-create:
      name: order-create
      partition: 5

